version: "3.7"
services:
  redis:
    container_name: redis
    image: redis
    networks:
      - network
    ports:
      - 6379:6379

  django:
    container_name: django
    image: django-image:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - static-volume:/srv/giganpyo-server/static
      - media-volume:/srv/giganpyo-server/media
    expose:
      - 8000
    networks:
      - network
    depends_on:
      - redis
      - celery_worker
    command: >
      bash -c "python manage.py makemigrations --settings=giganpyo.settings.production --noinput && python manage.py migrate --settings=giganpyo.settings.production && gunicorn -w 4 --env DJANGO_SETTINGS_MODULE=giganpyo.settings.production giganpyo.wsgi --bind 0.0.0.0:8000 --timeout=30"

  celery_worker:
    container_name: celery
    image: django-image:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - network
    command: >
      bash -c "celery -A giganpyo worker -l info"
    env_file:
      - .env

  nginx:
    container_name: nginx
    # nginx ver 설정
    image: nginx:1.20.2
    networks:
      - network
    volumes:
      - ${HOME_DIR}/giganpyo.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
    depends_on:
      - django

networks:
  network:

volumes:
  static-volume:
  media-volume: