# Generated by Django 4.0.3 on 2023-01-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tableapp', '0007_rename_id_table_table_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=1)),
                ('start_time', models.CharField(max_length=100)),
                ('start_h', models.PositiveSmallIntegerField()),
                ('start_m', models.PositiveSmallIntegerField()),
                ('fin_time', models.CharField(max_length=100)),
                ('fin_h', models.PositiveSmallIntegerField()),
                ('fin_m', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('credit', models.PositiveSmallIntegerField()),
                ('department', models.CharField(max_length=100, null=True)),
                ('is_required', models.CharField(max_length=100, null=True)),
                ('is_major', models.CharField(max_length=100, null=True)),
                ('is_offline', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('max_person', models.PositiveSmallIntegerField(null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=100)),
                ('select_person', models.PositiveSmallIntegerField(default=0, null=True)),
                ('professors', models.ManyToManyField(to='subjectapp.professor')),
                ('times', models.ManyToManyField(to='subjectapp.time')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart_subject', to='subjectapp.subject')),
                ('table', models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart_table', to='tableapp.table')),
            ],
        ),
    ]
