# Generated by Django 4.0.3 on 2023-01-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0005_alter_table_name'),
        ('subjectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_subject', to='subjectapp.subject'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_table', to='tableapp.table'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_major',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_offline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_required',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='select_person',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='session',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subjectprof',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_prof_professor', to='subjectapp.professor'),
        ),
        migrations.AlterField(
            model_name='subjectprof',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_prof_subject', to='subjectapp.subject'),
        ),
        migrations.AlterField(
            model_name='subjecttime',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_time_subject', to='subjectapp.subject'),
        ),
        migrations.AlterField(
            model_name='subjecttime',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_time_time', to='subjectapp.time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='time',
            name='fin_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
