# Generated by Django 4.0.3 on 2023-01-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0002_subject_location_alter_cart_subject_alter_cart_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='professors',
            field=models.ManyToManyField(to='subjectapp.professor'),
        ),
        migrations.AddField(
            model_name='subject',
            name='times',
            field=models.ManyToManyField(to='subjectapp.time'),
        ),
    ]
