# Generated by Django 4.0.3 on 2023-01-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0003_subject_professors_subject_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttime',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjecttime',
            name='time',
        ),
        migrations.DeleteModel(
            name='SubjectProf',
        ),
        migrations.DeleteModel(
            name='SubjectTime',
        ),
    ]
