# Generated by Django 4.0.3 on 2023-01-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0004_remove_subjecttime_subject_remove_subjecttime_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='max_person',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
