# Generated by Django 4.0.3 on 2023-01-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0005_subject_max_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='fin_h',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='fin_m',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='start_h',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='start_m',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
