FROM python:3.9.0

RUN apt update

WORKDIR /home/ubuntu/

RUN mkdir .virtualenvs

WORKDIR /home/ubuntu/.virtualenvs/

RUN pip install virtualenv

RUN virtualenv giganpyo

SHELL ["/bin/bash", "-c"]

RUN source giganpyo/bin/activate

SHELL ["/bin/sh", "-c"]

WORKDIR /home/ubuntu/giganpyo/

COPY mop_rm/Giganpyo-22-spring/timesite/ /home/ubuntu/giganpyo/

RUN pip install gunicorn

RUN pip install --upgrade google-api-python-client

RUN pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2

RUN pip install -r /home/ubuntu/giganpyo/requirements.txt

RUN python manage.py collectstatic --settings=config.settings.local --noinput

EXPOSE 8000

CMD ["bash", "-c", "python manage.py migrate --settings=config.settings.local --noinput && python manage.py migrate --settings=config.settings.local && gunicorn -w 4 --env DJANGO_SETTINGS_MODULE=config.settings.local config.wsgi --bind 0.0.0.0:8000 --timeout=30"]

