# Generated by Django 3.1.3 on 2022-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_subjecteval_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecteval',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='subjecteval',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjecteval',
            name='user',
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='is_offline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='SubjectEval',
        ),
    ]
