# Generated by Django 4.0.3 on 2023-01-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0004_alter_table_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='시간표', max_length=100, null=True),
        ),
    ]
