# Generated by Django 4.0.3 on 2023-01-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0005_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='시간표', max_length=100),
        ),
    ]
