# Generated by Django 4.0.3 on 2023-01-19 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tableapp', '0006_alter_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='id',
            new_name='table_id',
        )
    ]
